### ISSUE TITLE
Readme should call out where to get loadit

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-perf#13]
There are currently quite a few references to `loadit` but no reference of where to find it.

**Comment by abcyuyun** [comment]
do you know where to get loadit?

**Comment by abcyuyun** [comment]
> There are currently quite a few references to `loadit` but no reference of where to find it.

do you know where to get loadit?

**Comment by palourde** [comment]
I just added a link to the source code of loadit: https://github.com/sensu/sensu-perf/commit/2e5849f7e63fa4c63fe95c57507ab3f0b5b23afa.
