### ISSUE TITLE
Investigate "benchmark management" tools

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-perf#5]
I randomly ended up on [OpenBenchmarking.org](https://openbenchmarking.org/) and it reminded me that it would be great to have a somewhat systematic way to save, archive, compare, ... runs.

I don't know how well OpenBenchmarking would be suited to our needs (benchmarking a distributed system), but there may be nice tools out there that are a good fit for that?

**Comment by palourde** [comment]
We have the Google Spreadsheet + Grafana snapshots now; while it's not perfect, I think it's okay for our needs at the moment. Let's re-open this issue if we ever decide we need something more accurate!
